In [213]:
import numpy as np
import tensorflow as tf
from tensorflow.contrib import rnn

In [214]:
tf.reset_default_graph()
# Target log path
logs_path = '/Users/davidjoy/Desktop/log'
writer = tf.summary.FileWriter(logs_path)

#X_data = np.array([[[1,0,0,0,0,0,0],[0,1,0,0,0,0,0],[0,0,1,0,0,0,0],[0,0,0,1,0,0,0],[0,0,0,0,1,0,0],[0,0,0,0,0,1,0],[0,0,0,0,0,0,1],[0,0,0,0,0,0,1],[0,1,0,0,0,0,0],[0,0,1,0,0,0,0]]])
X_data = np.random.rand(1,3,26)

In [215]:
X_data.shape

(1, 3, 26)

In [216]:
# hyperparameters
n_neurons = 8

# parameters
n_inputs = X_data.shape[2]
n_steps = X_data.shape[1]
n_inputs,n_steps

(26, 3)

In [217]:
X = tf.placeholder(tf.float32,[None,n_steps,n_inputs])
X_seq = tf.unstack(X,axis=1)
cell = rnn.BasicRNNCell(num_units=n_neurons)
output,state = rnn.static_rnn(cell,X_seq,dtype=tf.float32)
output_st = tf.stack(output,axis=1)

In [218]:
# initialize the variables
init = tf.global_variables_initializer()

# train
with tf.Session() as sess:
    sess.run(init)
    writer.add_graph(sess.graph)
    feed_dict = {X: X_data}
    
    # print the shape
    X_seq1 = sess.run(X_seq,feed_dict=feed_dict)
    X_seq_shape = sess.run(tf.shape(X_seq), feed_dict=feed_dict)
    output1 = sess.run(output,feed_dict=feed_dict)
    output_shape = sess.run(tf.shape(output), feed_dict=feed_dict)
    state1 = sess.run(state,feed_dict=feed_dict)
    state_shape = sess.run(tf.shape(state), feed_dict=feed_dict)
    output_st_shape = sess.run(tf.shape(output_st), feed_dict=feed_dict)
    print('X_seq shape [batch_size, n_steps, n_inputs]: ', X_seq_shape)
    print('output shape [batch_size, n_neurons]: ', output_shape)
    print('state shape [batch_size, n_neurons]: ', state_shape)
    print('output_st shape [batch_size, n_steps, n_neurons]: ', output_st_shape)

    output_eval, state_eval = sess.run([output, state], feed_dict=feed_dict)
    print('Is the output of X2 equals to the state?', np.array_equal(output_eval[2], state_eval))
    print("\ttensorboard --logdir=%s" % (logs_path))
    print("Point your web browser to: http://localhost:6006/")

X_seq shape [batch_size, n_steps, n_inputs]:  [ 3  1 26]
output shape [batch_size, n_neurons]:  [3 1 8]
state shape [batch_size, n_neurons]:  [1 8]
output_st shape [batch_size, n_steps, n_neurons]:  [1 3 8]
Is the output of X2 equals to the state? True
	tensorboard --logdir=/Users/davidjoy/Desktop/log
Point your web browser to: http://localhost:6006/


In [222]:
X_seq1

[array([[ 0.28983417,  0.94875944,  0.27568939,  0.52146417,  0.02344077,
          0.12857966,  0.93653661,  0.29924423,  0.25478885,  0.13139975,
          0.09165226,  0.74572384,  0.34049323,  0.5035814 ,  0.3502267 ,
          0.04662772,  0.82934058,  0.85985821,  0.36623189,  0.32952082,
          0.6640057 ,  0.58670104,  0.05144461,  0.71061134,  0.21157382,
          0.91524786]], dtype=float32),
 array([[ 0.97101927,  0.59047049,  0.50110483,  0.62714767,  0.91974568,
          0.35089773,  0.47660625,  0.3940219 ,  0.65059072,  0.19135234,
          0.07294651,  0.5624373 ,  0.74463665,  0.95151162,  0.39508554,
          0.73668087,  0.73092419,  0.77264845,  0.40489185,  0.52165622,
          0.7420131 ,  0.55860782,  0.08904514,  0.96960837,  0.42475092,
          0.87034529]], dtype=float32),
 array([[ 0.06224494,  0.58815008,  0.70873582,  0.04820097,  0.23148338,
          0.75883621,  0.74834293,  0.43998525,  0.81857383,  0.37161288,
          0.24877051,  0.2070611

In [192]:
state1

array([[ 0.71290845,  0.27434731, -0.18854266,  0.254857  ,  0.50511104,
        -0.25663856,  0.33918527, -0.51156223]], dtype=float32)

In [220]:
output1[-1]

array([[-0.23012204, -0.78130561,  0.83628267,  0.12181109,  0.76163876,
        -0.67454571,  0.41057014,  0.53106993]], dtype=float32)

In [221]:
output1

[array([[ 0.23076978, -0.73699164,  0.65410572,  0.13606308,  0.63506216,
          0.15240327, -0.12397362, -0.52287555]], dtype=float32),
 array([[ 0.16157757, -0.81115305,  0.91662347,  0.26543981,  0.49397168,
          0.02633907,  0.03548642, -0.43388811]], dtype=float32),
 array([[-0.23012204, -0.78130561,  0.83628267,  0.12181109,  0.76163876,
         -0.67454571,  0.41057014,  0.53106993]], dtype=float32)]

In [235]:
import random
offset = random.randint(0,5)
offset

2